### ISSUE TITLE
Create a reminder email to sign up for peer groups

### ISSUE THREAD

**Issue by rebeccafae** [womenrising/womenrising#104]
An email should be sent the last day of the month to everyone who has not yet signed up, reminding them to participate in peer matches.
Once ready, you will need to get in touch with Rebecca @rebeccafae to add the task to Heroku Scheduler.

**Comment by timkleier** [comment]
@rebeccafae, I'd be glad to work on this. I'm assuming it's going to involve a rake task, based on logic related to the user, that triggers the UserMailer to send an email. Am I missing anything? Is there a specific user_mailer view I should use as a template? And I'm happy to craft the text of the email, but if you want it to say something specific, let me know.

**Comment by rebeccafae** [comment]
Thanks @timkleier 
Yes, that assumption is correct.
Matches are currently sent the 1st of the month, I know this issue says to send the email the last day of the month, but we may actually want to send it a few days before.

Use can use whichever view you like as a template, the peer_mail was most recently updated, but if you like another better that is fine with me. As far as text we'll have to ask @KateCatlin about that, she has been drafting and sending all these emails from MailChimp. But if she is not able to respond in time, I'm sure that she will be happy with whatever text you choose!

**Comment by timkleier** [comment]
@rebeccafae, I'm submitting a pull request and I set it to go out three days before the end of the month. @KateCatlin, feel free to make any changes to the text of the email, I just threw some basic text in there.
