### ISSUE TITLE
Chore: Migration live-in-detroit users to Detroit location

### ISSUE THREAD

**Issue by aelydens** [womenrising/womenrising#25]
Rake task

Change users who have `live_in_detroit: true` to have the Location id for detroit

**Comment by rebeccafae** [comment]
location = Location.find_by_city 'Detroit'
User.update location_id: location.id

**Comment by rebeccafae** [comment]
rake task is ready, but still need to use it

**Comment by rebeccafae** [comment]
Completed on staging, leaving this here until complete on production
