### ISSUE TITLE
Mentor matching waitlist

### ISSUE THREAD

**Issue by aelydens** [womenrising/womenrising#27]

**Comment by KateCatlin** [comment]
Also included in this -- We need some way to cache mentors and mentee requests rather than just denying those who request a mentor automatically.

**Comment by rebeccafae** [comment]
As a mentee when requesting a mentor, if none are available, you should get a notice that you have been put on a waitlist/queue for mentors. The next time a mentor becomes available, it should automatically match the mentor with the next mentee on the queue.
