### ISSUE TITLE
Mentor validation cleanup

### ISSUE THREAD

**Issue by aelydens** [womenrising/womenrising#28]
Mentorship has an unusual way of validation/adding errors. This should be changed to conform w/ convention.

**Comment by rebeccafae** [comment]
http://guides.rubyonrails.org/active_record_validations.html

**Comment by kimschles** [comment]
I'll take this story. I will write tests to test the validations and then refactor the code. 

Note to self: 
- http://culttt.com/2016/07/06/writing-integration-tests-ruby-rails/
- http://guides.rubyonrails.org/testing.html

**Comment by rebeccafae** [comment]
This story should actually happen after, or with #28, because otherwise it would have to change again.
