### ISSUE TITLE
Splice matching

### ISSUE THREAD

**Issue by aelydens** [womenrising/womenrising#29]
Users looking for peer groups should be matched monthly using a laxer approach to selection.

We should select users by location only.**

- Do we want to select based on career level? 
- Can we toggle selection methods on and off per month?
- User groups should be 3 or 4 people, but a two person group of leftovers is ok.

**On hold until Kate gives feedback.

**Comment by rebeccafae** [comment]
@aelydens Has anyone spoken to Kate about this? This would come in handy while removing `live_in_detroit` so we don't have to re-write all that logic

**Comment by KateCatlin** [comment]
First and foremost -- thank you for your hours of work and for bringing your unique viewpoints to the table! 

Here are my thoughts: 
1.) Thumbs up on simplifying peer groups to location only to simplify them. Let's do it. 
2.) Can we structure the code in such a way that it leaves it open to adding in more filters later? Like future Women Rising hack nights or volunteer hours? I think there will still be features that will be important to people, but I'm not sure which one(s) is(/are) the most important. My new IDEO background says simplify until you have feedback. Thus, I like the idea of simplifying it so we can expedite launch in Colorado and but leaving room to add filters for matches later. 

What do you two think about that as a strategy? Going for #Agile #Designthinking

**Comment by aelydens** [comment]
@KateCatlin love it. This makes the code for selection super simple, and yeah, it can absolutely be designed in a way where it's easy to additional selection criteria. 

@rfjackson11, does that give you enough to go on? With this, you can basically remove almost all the peer groups matching logic. Let me know if you want to chat more about this!

**Comment by rebeccafae** [comment]
That sounds great! I can keep moving forward with this, no problem.
