### ISSUE TITLE
Chore: Clean up code

### ISSUE THREAD

**Issue by aelydens** [womenrising/womenrising#30]
Consistently make improvements to code style to conform with our styleguide. (link in repo)

**Comment by rebeccafae** [comment]
https://github.com/bbatsov/ruby-style-guide and https://github.com/bbatsov/rails-style-guide

**Comment by timkleier** [comment]
@rebeccafae, if I installed Rubocop and made fixes until it passed, would that be sufficient?

**Comment by rebeccafae** [comment]
@timkleier yes that would be great!
