### ISSUE TITLE
User can select "other" location

### ISSUE THREAD

**Issue by aelydens** [womenrising/womenrising#31]
User can select "other" from location dropdown.

Users are prompted to type in an alternative location.
We receive this location and store it somewhere.

We need a way to make a judgment at some point in the future as to where to open additional WR chapters, so we need a way to document future location suggestions.

**Comment by rebeccafae** [comment]
@westonplatter @aelydens 
We came up with the idea of saving the zipcode. Then down the road we can query regions based on the zipcodes.
