### ISSUE TITLE
Make "click to participate" more intuitive. 

### ISSUE THREAD

**Issue by KateCatlin** [womenrising/womenrising#47]
Right now it's hard to find. You have to go to your profile and then see "Click to not participate this month" and figure out to click it. 

A couple of options: 
-- Can we make it a button? Like a big fat button close to the top of the page? 
-- Even better: Can we make it a button that you're prompted with that pops up when you view your profile?

**Comment by rebeccafae** [comment]
@KateCatlin please test on staging. Comment and tag me on here when I can move it to production. (Trying out this process)
