### ISSUE TITLE
Did mentee reach out? 

### ISSUE THREAD

**Issue by KateCatlin** [womenrising/womenrising#49]
A large issue is mentees getting assigned a mentor and then not following up. Others are eagerly awaiting mentors and not getting them because we don't have enough. 

This is a reach goal but in an ideal world: 
1.) Mentors who match would receive a follow-up email asking if they were contacted by their assigned mentee. They can answer with one click of a button. 
2.) We somehow tag the mentee with this data. 
3.) Those who didn't receive a mentor match last month have first priority on matching next month. Those who actually follow up with the mentor have a weighted higher chance of getting one next time they request. Those who got a mentor and didn't follow up are de-prioritized from getting a mentor next month.

**Comment by rebeccafae** [comment]
Closing this and moving information to feedback loop issues (#63 and #55)
