### ISSUE TITLE
Errors upon requesting a mentor

### ISSUE THREAD

**Issue by KateCatlin** [womenrising/womenrising#51]
I often receive these types of issues: 
"Hi Kate, this looks really promising ! I'm having trouble signing up for receiving peer mentoring (error: specific question). Could you help include my name for this too?" 

The error thrown always seems to be "specific question." Not sure what the underlying issue is and we may solve this just by refactoring the mentor request line.

**Comment by rebeccafae** [comment]
@marshallds Is this the same error you were talking to me about yesterday, and are fixing in your current branch?
