### ISSUE TITLE
Automate monthly peer group matching

### ISSUE THREAD

**Issue by rebeccafae** [womenrising/womenrising#65]
Automate the rake task using [Heroku Scheduler](https://devcenter.heroku.com/articles/scheduler)
Add logging to the task, so we can keep an eye on it and make sure it is all working correctly. Preferably log to Rollbar (we will need to add Rollbar to the app on Heroku first)

**Comment by rebeccafae** [comment]
@KateCatlin would you like the matches to be run on the 1st of every month?

**Comment by KateCatlin** [comment]
That's actually a great idea. 

Then I'll start scheduling reminder emails the week _before_ rather than the first week.
